version: "3"

services:
  btc-crawler:
    build: ./bitnodes-master
    networks:
      - redis-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379:6379"]
    networks:
      - redis-tier

#  worker:
#    build:
#      context: ./worker
#    depends_on:
#      - "redis"
#    networks:
#      - back-tier


networks:
  redis-tier:
