version: '3.7'

services:
  btc-crawler:
    build: ./bitnodes-master
    volumes:
      - ./bitnodes-master:/bitnodes

  redis:
    image: redis:alpine

  postgres:
    container_name: testpg
    environment:
      POSTGRES_DB: btc_crawl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:11.4
    volumes:
      - ./btc_crawl.sql:/docker-entrypoint-initdb.d/init.sql
      - btc_crawl_data:/var/lib/postgresql/data
#    expose:
#      - 5432

volumes:
  btc_crawl_data:
    external: false
